Repository SFDO-Tooling/CumulusCI, pull requests merged in 2021-09, with the labels that each got.

#2827 Capture console output from tasks
  .pre-commit-config.yaml
  cumulusci/core/tasks.py
  cumulusci/core/tests/test_tasks.py
  cumulusci/tasks/robotframework/robotframework.py
  cumulusci/tasks/robotframework/tests/test_robot_parallel.py
  cumulusci/tasks/robotframework/tests/test_robotframework.py
  cumulusci/utils/logging.py
  pyproject.toml
Labels: in review

#2845 Verbose mode for flow info
  cumulusci/cli/flow.py
  cumulusci/cli/tests/test_flow.py
  cumulusci/core/flowrunner.py
  cumulusci/core/tests/test_flowrunner.py
Labels: in progress

#2887 Remove terminaltables from CLI table.
  cumulusci/cli/flow.py
  cumulusci/cli/org.py
  cumulusci/cli/service.py
  cumulusci/cli/task.py
  cumulusci/cli/tests/test_flow.py
  cumulusci/cli/tests/test_org.py
  cumulusci/cli/tests/test_service.py
  cumulusci/cli/tests/test_task.py
  cumulusci/cli/tests/test_ui.py
  cumulusci/cli/ui.py
  cumulusci/tasks/salesforce/composite.py
  cumulusci/tasks/salesforce/package_upload.py
  cumulusci/tasks/salesforce/tests/test_PackageUpload.py
  cumulusci/tasks/salesforce/tests/test_composite.py
  cumulusci/tasks/salesforce/users/permsets.py
  requirements/dev.txt
  requirements/prod.in
  requirements/prod.txt
Labels: review assigned
