Repository SFDO-Tooling/CumulusCI, pull requests merged in 2021-02, with the labels that each got.

#2042 Doc reorg: Scratch Orgs
  docs/scratch_orgs.rst
Labels: documentation, in review

#2371 New preflight check task - recordtypes.GetHasRecordTypes for Sobject
  cumulusci/cumulusci.yml
  cumulusci/tasks/preflight/recordtypes.py
  cumulusci/tasks/preflight/tests/test_recordtypes.py
Labels: enhancement, feature

#2102 Doc Reorg: Connect Persistent Orgs
  docs/connected_orgs.rst
Labels: documentation, in review

#2345 Update AUTHORS.rst
  AUTHORS.rst
  CONTRIBUTING.rst
Labels: documentation

#2289 Feature/doc reorg managed package
  docs/images/cci_service_list.png
  docs/managed_package.rst
Labels: documentation

#2159 Doc reorg: Develop A Project
  docs/cheat_sheet.rst
  docs/cookbook.rst
  docs/dev.rst
Labels: documentation

#2150 Doc reorg: Continuous Integration
  docs/conf.py
  docs/continuous_integration.rst
  docs/cumulusci_flow.rst
  docs/github_actions.rst
  docs/tasks.rst
Labels: documentation

#2298 Feature/doc reorg unlocked
  docs/unlocked_package.rst
Labels: documentation

#2069 Doc Reorg: Unpackaged Metadata & Metadata ETL
  docs/index.rst
  docs/metadata_etl.rst
  docs/unpackaged.rst
Labels: documentation, in review

#2320 [Doc Reorg] Cheat Sheet
  docs/cheat_sheet.rst
  docs/concepts.rst
Labels: documentation

#2039 Doc reorg: Introduction
  docs/faq.rst
  docs/intro.rst
  docs/learn_more.rst
  docs/read_next.rst
Labels: documentation, in review
