Repository SFDO-Tooling/CumulusCI, pull requests merged in 2022-06, with the labels that each got.

#3149 Add property in OrgConfig to check for advanced survey features
  cumulusci/core/config/org_config.py
  cumulusci/core/config/tests/test_config.py
Labels: enhancement

#3227 Fix release notes config filename
  .github/release.yml
Labels: ignore-for-release

#3209 Merge yaml config with config present from org file
  cumulusci/core/keychain/encrypted_file_project_keychain.py
  cumulusci/core/keychain/tests/conftest.py
  cumulusci/core/keychain/tests/test_encrypted_file_project_keychain.py
Labels: bug

#3239 `metadeploy_publish` consumes legal targets for supported orgs
  cumulusci/schema/cumulusci.jsonschema.json
  cumulusci/tasks/metadeploy.py
  cumulusci/tasks/tests/test_metadeploy.py
  cumulusci/utils/yaml/cumulusci_yml.py
Labels: enhancement

#3243 Add update_profile support for record type layouts
  AUTHORS.rst
  cumulusci/tasks/salesforce/tests/test_ProfileGrantAllAccess.py
  cumulusci/tasks/salesforce/update_profile.py
Labels: enhancement

#3235 Make OrgSettings also deploy objectSettings, if present
  cumulusci/tasks/salesforce/org_settings.py
  cumulusci/tasks/salesforce/tests/test_org_settings.py
Labels: enhancement

#3249 Document new `custom` section
  docs/config.md
Labels: ignore-for-release

#3254 Correct FeatureParameterString to FeatureParameterDate
  cumulusci/salesforce_api/package_zip.py
  cumulusci/version.txt
Labels: bug

#3252 Clarify field permission errors
  cumulusci/tasks/bulkdata/mapping_parser.py
Labels: ignore-for-release

#3255 Provide more context for git errors
  cumulusci/core/github.py
  cumulusci/core/tests/test_github.py
Labels: ignore-for-release
