Repository SFDO-Tooling/CumulusCI, pull requests merged in 2022-07, with the labels that each got.

#3277 Fix `metadeploy_publish` error caused by supported_orgs case-sensitivity
  cumulusci/tasks/metadeploy.py
  cumulusci/tasks/tests/test_metadeploy.py
Labels: bug

#3261 Extract MetaDeploy API from publish task
  cumulusci/cli/tests/test_plan.py
  cumulusci/core/metadeploy/api.py
  cumulusci/core/metadeploy/tests/test_api.py
  cumulusci/tasks/metadeploy.py
  cumulusci/tasks/tests/test_metadeploy.py
  pyproject.toml
Labels: ignore-for-release

#3270 CumulusCI now supports pinning dependencies on other projects
  cumulusci/cli/project.py
  cumulusci/core/dependencies/dependencies.py
  cumulusci/core/dependencies/resolvers.py
  cumulusci/core/dependencies/tests/conftest.py
  cumulusci/core/dependencies/tests/test_resolvers.py
  cumulusci/schema/cumulusci.jsonschema.json
  cumulusci/tasks/github/release.py
  cumulusci/tasks/metaxml.py
  cumulusci/utils/yaml/cumulusci_yml.py
  docs/dev.md
Labels: enhancement

#3265 Filtering for Schema caching and querying
  cumulusci/salesforce_api/filterable_objects.py
  cumulusci/salesforce_api/org_schema.py
  cumulusci/salesforce_api/org_schema_models.py
  cumulusci/utils/tests/cassettes/ManualEdit_test_describe_to_sql.yaml
  cumulusci/utils/tests/test_org_schema.py
Labels: ignore-for-release

#3282 Include default SFDX gitignore files
  cumulusci/files/templates/project/dot-gitignore
Labels: ignore-for-release

#3296 Omnistudio Retrieve/Deploy Tasks
  cumulusci/cumulusci.yml
  cumulusci/tasks/vlocity/exceptions.py
  cumulusci/tasks/vlocity/tests/test_vlocity.py
  cumulusci/tasks/vlocity/vlocity.py
Labels: enhancement

#3297 Suppress third-party warnings and error on `ClassMovedWarning`
  pyproject.toml
Labels: ignore-for-release

#3298 Validate MetaDeploy plans in cumulusci.yml
  cumulusci/schema/cumulusci.jsonschema.json
  cumulusci/utils/yaml/cumulusci_yml.py
  cumulusci/utils/yaml/tests/test_cumulusci_yml.py
Labels: enhancement

#3295 Mask sensitive attributes in cci service info output
  cumulusci/cli/service.py
  cumulusci/cli/tests/test_service.py
  cumulusci/core/github.py
  cumulusci/core/tests/test_github.py
  cumulusci/core/tests/test_utils.py
  cumulusci/core/utils.py
  cumulusci/cumulusci.yml
  cumulusci/schema/cumulusci.jsonschema.json
  cumulusci/utils/yaml/cumulusci_yml.py
Labels: enhancement

#3303 MetaData ETL Task - `add_remote_site_settings`
  cumulusci/cumulusci.yml
  cumulusci/tasks/metadata_etl/base.py
  cumulusci/tasks/metadata_etl/remote_site_settings.py
  cumulusci/tasks/metadata_etl/tests/test_remote_site_settings.py
  cumulusci/tasks/vlocity/tests/test_vlocity.py
  cumulusci/tasks/vlocity/vlocity.py
Labels: enhancement
