Repository SFDO-Tooling/CumulusCI, pull requests merged in 2022-10, with the labels that each got.

#3361 Support updates and upserts with blank dates represented by strings
  cumulusci/tasks/bulkdata/step.py
  cumulusci/tasks/bulkdata/tests/test_step.py
Labels: bug

#3289 Add another: to git-blame-ignore
  .git-blame-ignore-revs
Labels: ignore-for-release

#3338 Update runner for release workflow
  .github/workflows/release.yml
Labels: ignore-for-release

#3354 Clean up references to legacy -o syntax
  cumulusci/tasks/apex/testrunner.py
  cumulusci/tasks/bulkdata/mapping_parser.py
Labels: ignore-for-release

#3380 Clean up test_datasets_e2e output
  cumulusci/core/tests/test_datasets_e2e.py
Labels: ignore-for-release

#3256 Add support for GitHub Enterprise
  cumulusci/cli/service.py
  cumulusci/cli/tests/test_service.py
  cumulusci/core/config/__init__.py
  cumulusci/core/config/project_config.py
  cumulusci/core/config/tests/test_config.py
  cumulusci/core/github.py
  cumulusci/core/keychain/base_project_keychain.py
  cumulusci/core/keychain/tests/conftest.py
  cumulusci/core/keychain/tests/test_base_project_keychain.py
  cumulusci/core/source/github.py
  cumulusci/core/tests/test_github.py
  cumulusci/cumulusci.yml
  cumulusci/tasks/github/base.py
  cumulusci/tasks/github/publish.py
  cumulusci/tasks/salesforce/install_package_version.py
  cumulusci/utils/git.py
  cumulusci/utils/tests/test_git.py
  docs/get-started.md
  docs/headless.md
  requirements/prod.txt
Labels: critical-change

#3386 Commit-status dependency resolution falls back to main branch
  cumulusci/core/config/project_config.py
  cumulusci/core/config/tests/test_config.py
  cumulusci/core/dependencies/resolvers.py
  cumulusci/core/dependencies/tests/conftest.py
  cumulusci/core/dependencies/tests/test_dependencies.py
  cumulusci/core/dependencies/tests/test_resolvers.py
  cumulusci/cumulusci.yml
  docs/dev.md
Labels: enhancement

#3382 Remove references to brew
  cumulusci/tests/test_utils.py
  cumulusci/utils/__init__.py
Labels: critical-change

#3392 Turn on jinja2 autoescaping
  cumulusci/cli/project.py
Labels: ignore-for-release

#3403 Add support for InstallKey, sourceOrg, release keys on 2GP version create
  cumulusci/tasks/create_package_version.py
  cumulusci/tasks/tests/test_create_package_version.py
Labels: enhancement

#3286 Add `push_upgrade_org` flow to test in simulated push upgrade environment
  cumulusci/cumulusci.yml
  docs/cheat-sheet.md
  docs/concepts.md
Labels: enhancement

#3402 Add type annotations to core classes
  cumulusci/core/config/base_task_flow_config.py
  cumulusci/core/flowrunner.py
  cumulusci/core/runtime.py
  cumulusci/core/tasks.py
Labels: ignore-for-release

#3414 Type base and project configs
  cumulusci/core/config/base_config.py
  cumulusci/core/config/project_config.py
  cumulusci/core/github.py
Labels: ignore-for-release

#3420 Remove homebrew workflow
  .github/workflows/build_homebrew.yml
  Makefile
Labels: ignore-for-release
