Repository SFDO-Tooling/CumulusCI, pull requests merged in 2023-09, with the labels that each got.

#3365 Add better error handling for empty or invalid org and service env vars
  cumulusci/core/exceptions.py
  cumulusci/core/keychain/encrypted_file_project_keychain.py
  cumulusci/core/keychain/tests/test_encrypted_file_project_keychain.py
Labels: cla:missing

#3595 Remove lines that DG says are an anti-pattern and Python interpreter calls deprecated
  cumulusci/core/tests/__init__.py
  cumulusci/salesforce_api/__init__.py
  cumulusci/tasks/__init__.py
Labels: ignore-for-release, cla:missing

#3645 Add guard for empty body to github_release_report
  cumulusci/tasks/github/release_report.py
  cumulusci/tasks/github/tests/test_release_report.py
  cumulusci/tasks/github/tests/util_github_api.py
Labels: bug, review assigned

#3654 Query with install_key in promote_package_version (via @zenibako)
  AUTHORS.rst
  cumulusci/cumulusci.yml
  cumulusci/tasks/create_package_version.py
  cumulusci/tasks/salesforce/promote_package_version.py
  cumulusci/tasks/tests/test_create_package_version.py
  cumulusci/tasks/tests/test_promote_package_version.py
  cumulusci/utils/salesforce/soql.py
  cumulusci/utils/salesforce/tests/test_soql.py
Labels: enhancement, cla:signed

#3660 W-12214520: Adding ApexTestSuite support in run_tests
  cumulusci/tasks/apex/testrunner.py
  cumulusci/tasks/apex/tests/test_apex_tasks.py
Labels: enhancement, in review
